SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE proc [dbo].[CASA_NPA_IntegrationDetails_Main]

as

begin



insert into CASA_NPA_IntegrationDetails(
NCIF_Id
,NCIF_Changed
,SrcSysAlt_Key
,NCIF_EntityID
,CustomerId
,CustomerName
,PAN
,AddharNo
,GroupId
,GroupCode
,GroupDesc
,NCIF_AssetClassAlt_Key
,NCIF_NPA_Date
,AccountEntityID
,CustomerACID
,SanctionedLimit
,DrawingPower
,PrincipleOutstanding
,Balance
,Overdue
,DPD_Overdue_Loans
,DPD_Interest_Not_Serviced
,DPD_Overdrawn
,DPD_Renewals
,DPD
,MaxDPD
,WriteOffFlag
,Segment
,SubSegment
,ProductCode
,ProductDesc
,Settlement_Status
,AC_AssetClassAlt_Key
,AC_NPA_Date
,AstClsChngByUser
,AstClsChngDate
,AstClsChngRemark
,MOC_Status
,MOC_Date
,MOC_ReasonAlt_Key
,AuthorisationStatus
,EffectiveFromTimeKey
,EffectiveToTimeKey
,CreatedBy
,DateCreated
,ModifiedBy
,DateModified
,ApprovedBy
,DateApproved
,Remark
,ProductType
,ActualOutStanding
,PrevNICF_Id
,ProductAlt_Key)
select 
NCIF_Id
,NCIF_Changed
,SrcSysAlt_Key
,NCIF_EntityID
,CustomerId
,CustomerName
,PAN
,AddharNo
,GroupId
,GroupCode
,GroupDesc
,NCIF_AssetClassAlt_Key
,NCIF_NPA_Date
,AccountEntityID
,CustomerACID
,SanctionedLimit
,DrawingPower
,PrincipleOutstanding
,Balance
,Overdue
,DPD_Overdue_Loans
,DPD_Interest_Not_Serviced
,DPD_Overdrawn
,DPD_Renewals
,DPD
,MaxDPD
,WriteOffFlag
,Segment
,SubSegment
,ProductCode
,ProductDesc
,Settlement_Status
,AC_AssetClassAlt_Key
,AC_NPA_Date
,AstClsChngByUser
,AstClsChngDate
,AstClsChngRemark
,MOC_Status
,MOC_Date
,MOC_ReasonAlt_Key
,AuthorisationStatus
,EffectiveFromTimeKey
,EffectiveToTimeKey
,CreatedBy
,DateCreated
,ModifiedBy
,DateModified
,ApprovedBy
,DateApproved
,Remark
,ProductType
,ActualOutStanding
,PrevNICF_Id
,ProductAlt_Key from CASA_NPA_IntegrationDetails_temp 

end
GO