SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[Validate_DataUpload_STD_ASSET_CAT_MASTER_BKP25042024] --'1','ABDHSWG/LNC',26923,26923,'ZASH122'
@OperationFlag			INT
,@UserLoginID				VARCHAR(30)
, @EFFECTIVEFROMTIMEKEY INT
, @EFFECTIVETOTIMEKEY INT
,@STD_ASSET_CATName VARCHAR(50)
, @Result		INT=0 OUTPUT
WITH RECOMPILE  
AS  

  
BEGIN
			DECLARE @STD_ASSET_CAT_Key INT=(select max(STD_ASSET_CAT_Key)+10 from DIM_STD_ASSET_CAT where STD_ASSET_CAT_Key not in (900))

			IF @OperationFlag=1 
			BEGIN
			IF (EXISTS (SELECT 1 FROM DIM_STD_ASSET_CAT where --STD_ASSET_CAT_Key=@STD_ASSET_CAT_Key AND /*NONEED AS WE ARE SETTING THE ALTKEY*/
								STD_ASSET_CATShortName=@STD_ASSET_CATName ))
									BEGIN
										 --Rollback tran
										SET @Result=-6
										PRINT  'SAME VALUES ALREADY EXISTS 1, KINDLY UPDATE IF ANY CHANGES IN THE EXISTING CODE'+'RESULT : '+CAST(@Result AS VARCHAR(2))
										RETURN @Result
										
									END
									ELSE
									SET @Result=1
										PRINT  'NEW CODE FOUND - BEGINNING WITH INSERTION ,'+'RESULT : '+CAST(@Result AS VARCHAR(2))
										RETURN @Result
										
END
 
 END
GO