SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE Proc [dbo].[Ganseva_SCHEME_CODE_NUll]
as
Begin
insert into ETL_Validation_Details(
SYSTEM,ENTERPRISE_CIF,CLIENT_ID,CUSTOMER_NAME,ACCOUNT_NUMBER,LIMIT,TOTAL_OUTSTANDING,PRINCIPAL_OUTSTANDING
,DPD,CLASSIFICATION,NPA_DATE,SETTLEMENT_STATUS,WRITE_OFF_FLAG,GROUP_ID,GROUP_CODE,GROUP_DESC,SEGMENT
,SUB_SEGMENT,PAN,AADHAR_UID,SCHEME_TYPE,SCHEME_CODE,SCHEME_DESCRIPTION,DRAWING_POWER,DPD_OVERDUE_LOANS
,DPD_INTEREST_NOT_SERVICED,DPD_OVERDRAWN,DPD_RENEWALS,OVERDUE_AMOUNT)
select SYSTEM ,ENTERPRISE_CIF ,[CLIENT ID (SOURCE SYSTEM)] ,CUSTOMER_NAME ,[ACCOUNT NUMBER],LIMIT 
,[TOTAL OUTSTANDING],[PRINCIPAL  OUTSTANDING] ,DPD ,CLASSIFICATION ,[NPA DATE] ,[SETTLEMENT STATUS] 
,[WRITE OFF FLAG],[GROUP ID] ,[GROUP CODE] ,[GROUP DESC] ,SEGMENT ,[SUB SEGMENT] ,PAN  ,[AADHAR UID] 
,[SCHEME TYPE] ,[SCHEME CODE  PRODUCT CODE] ,[SCHEME  PRODUCT CODE DESCRIPTION] ,[DRAWING POWER (IN INR)] 
,[DPD - OVERDUE LOANS] ,[DPD - INTEREST NOT SERVICED] ,[DPD - OVERDRAWN] ,[DPD - RENEWALS] 
,[OVERDUE AMOUNT]  From InduslndStg.dbo.Ganseva_Stg where [SCHEME CODE  PRODUCT CODE]=''
END
GO