SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[COLLATERAL_DELINK_PROCESS] 
@TIMEKEY INT 
AS
BEGIN

DECLARE @DATE DATE= (SELECT DATE FROM SysDataMatrix WHERE TimeKey=@TIMEKEY)
PRINT @DATE 

/*CREATING STRUCTURE FOR COLLATERAL_DELINK_DATE_AdvSecurityDetailL*/

/*INSERTING VALUE IN COLLATERAL_DELINK_DATE_AdvSecurityDetailL WHERE COLLATERAL DELINK DATE IS AVAILABLE*/
INSERT INTO COLLATERAL_DELINK_DATE_AdvSecurityDetailL 
SELECT * FROM [CURDAT].[AdvSecurityDetail] WHERE isnull(COLL_DELINK_DATE,'2099-12-31')<@DATE AND EffectiveFromTimeKey<=@TIMEKEY AND EffectiveToTimeKey>=@TIMEKEY

/*DELETING VALUE IN [CURDAT].[AdvSecurityDetail] WHERE COLLATERAL DELINK DATE IS AVAILABLE*/
DELETE FROM [CURDAT].[AdvSecurityDetail] WHERE isnull(COLL_DELINK_DATE,'2099-12-31')<@DATE AND EffectiveFromTimeKey<=@TIMEKEY AND EffectiveToTimeKey>=@TIMEKEY

END
GO