SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE  [dbo].[PROVISION_COMPUTATION_REDUCTION]  (
@TIMEKEY INT
)
AS
BEGIN
	
	DECLARE @SubSTD SMALLINT=(SELECT AssetClassAlt_Key FROM DimAssetClass WHERE AssetClassShortNameEnum='SUB' AND EffectiveFromTimeKey<=@TimeKey AND EffectiveToTimeKey>=@TimeKey)
/*CREATING TEMP TABLE FOR LIVE DATE DATA ONLY*/

DROP TABLE IF EXISTS #NPA_INTEGRATIONDETAILS
	SELECT * INTO #NPA_INTEGRATIONDETAILS FROM NPA_INTEGRATIONDETAILS NID WHERE NID.EffectiveFromTimeKey<=@TIMEKEY AND NID.EffectiveToTimeKey>=@TIMEKEY 


/*EXPIRING RECORDS IN REDUCTION TABLE WHICH CHANGED CLASSIFICATION FROM SUB-STANDARD TO ANY OTHER CLASSIFICATION*/

--IDENTIFYING CLISSIFICATION CHANGE STATUS COMPARED TO THE PROVISION REDUCTION STATUS
	SELECT NID.CustomerACID,NID.NCIF_AssetClassAlt_Key,PR.SECURED_PERCENTAGE,PR.UNSECURED_PERCENTAGE  
	INTO #PROVISION_RETAINED_DUETOCLASS_CHANGE
	FROM #NPA_INTEGRATIONDETAILS NID INNER JOIN CURDAT.PROVISION_REDUCTION PR 
	ON 
		NID.CustomerACID=PR.CustomerACID AND 
		ISNULL(NID.NCIF_AssetClassAlt_Key,'')<>@SubSTD
	WHERE NID.EffectiveFromTimeKey<=@TIMEKEY AND NID.EffectiveToTimeKey>=@TIMEKEY 
	AND PR.EffectiveFromTimeKey<=@TIMEKEY AND PR.EffectiveToTimeKey>=@TIMEKEY 

SELECT * FROM #PROVISION_RETAINED_DUETOCLASS_CHANGE

	UPDATE PR SET  PR.EffectiveToTimeKey=@TIMEKEY-1
	FROM #NPA_INTEGRATIONDETAILS NID INNER JOIN CURDAT.PROVISION_REDUCTION PR 
	ON 
		NID.CustomerACID=PR.CustomerACID AND 
		ISNULL(NID.NCIF_AssetClassAlt_Key,'')<>PR.NCIF_AssetClassAlt_Key
	WHERE NID.EffectiveFromTimeKey<=@TIMEKEY AND NID.EffectiveToTimeKey>=@TIMEKEY 
	AND PR.EffectiveFromTimeKey<=@TIMEKEY AND PR.EffectiveToTimeKey>=@TIMEKEY 

--MAINTAINING HISTORY FOR EXPIRED PROVISION REDUCTION

--SELECT * INTO PROVISION_REDUCTION_HIST FROM  CURDAT.PROVISION_REDUCTION WHERE 1=2

INSERT INTO PROVISION_REDUCTION_HIST
SELECT * FROM CURDAT.PROVISION_REDUCTION
WHERE CUSTOMERACID NOT IN (
SELECT CUSTOMERACID FROM CURDAT.PROVISION_REDUCTION WHERE EffectiveFromTimeKey<=@TIMEKEY AND 
												EffectiveToTimeKey>=@TIMEKEY)


--DELETING EXPIRED RECORDS FROM MAIN TABLE

DELETE FROM CURDAT.PROVISION_REDUCTION
WHERE CUSTOMERACID NOT IN (
SELECT CUSTOMERACID FROM CURDAT.PROVISION_REDUCTION WHERE EffectiveFromTimeKey<=@TIMEKEY AND 
												EffectiveToTimeKey>=@TIMEKEY)


/*CREATING TEMP TABLE WHERE REDUCTION ACCOUNTS ARE GETTING SEGREGATED FROM MAIN TABLE FRO RE CALCULATION*/

DROP TABLE IF EXISTS #PROVISION_TOBE_REDUCED
	SELECT NID.CustomerACID,NID.NCIF_AssetClassAlt_Key,PR.SECURED_PERCENTAGE,PR.UNSECURED_PERCENTAGE
	,NID.SecuredAmt*ISNULL(PR.SECURED_PERCENTAGE,0) NEW_SECPROV,NID.UnSecuredAmt*ISNULL(PR.UNSECURED_PERCENTAGE,0) NEW_UNSECPROV 
	INTO #PROVISION_TOBE_REDUCED
	FROM #NPA_INTEGRATIONDETAILS NID INNER JOIN CURDAT.PROVISION_REDUCTION PR 
	ON 
		NID.CustomerACID=PR.CustomerACID 
		--AND NID.NCIF_AssetClassAlt_Key=@SubSTD
	WHERE NID.EffectiveFromTimeKey<=@TIMEKEY AND NID.EffectiveToTimeKey>=@TIMEKEY 
	AND PR.EffectiveFromTimeKey<=@TIMEKEY AND PR.EffectiveToTimeKey>=@TIMEKEY 

SELECT *FROM #PROVISION_TOBE_REDUCED
/*PROVISION REDUCTION IN MAIN TABLE*/

	--SELECT NID.CustomerACID,NID.NCIF_AssetClassAlt_Key,PR.SECURED_PERCENTAGE,PR.UNSECURED_PERCENTAGE,(NEW_SECPROV+NEW_UNSECPROV),NID.*
	
	UPDATE NID SET TotalProvision=(ISNULL(NEW_SECPROV,0)+ISNULL(NEW_UNSECPROV,0))
					--,SEC_PROVPER_OLD=PR.SECURED_PERCENTAGE	--this column is commented because with Deployment of Provision policy enhancement 04042024 ON PROD
					--,UNSEC_PROVPER_OLD=PR.UNSECURED_PERCENTAGE    --this column is commented because with Deployment of Provision policy enhancement 04042024 ON PROD
					,Provsecured=ISNULL(NEW_SECPROV,0)
					,ProvUnsecured=ISNULL(NEW_UNSECPROV,0)
	FROM NPA_INTEGRATIONDETAILS NID INNER JOIN #PROVISION_TOBE_REDUCED PR 
	ON 
		NID.CustomerACID=PR.CustomerACID 
		--AND NID.NCIF_AssetClassAlt_Key=@SubSTD
	WHERE NID.EffectiveFromTimeKey<=@TIMEKEY AND NID.EffectiveToTimeKey>=@TIMEKEY 

END
GO