SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


CREATE PROCEDURE [dbo].[MOC_CORRECTION]
AS
BEGIN

DECLARE @UPLOADID VARCHAR(MAX)
DECLARE @MONTHENDDATE DATE = (SELECT DATEADD(DAY,-1,MONTHFIRSTDATE) FROM SYSDATAMATRIX WHERE CURRENTSTATUS='C')
DECLARE @MONTHENDTIMEKEY INT = (SELECT TimeKey FROM SYSDATAMATRIX WHERE Date=@MONTHENDDATE)

PRINT 'MONTHENDDATE : '
PRINT @MONTHENDDATE
PRINT 'MONTHENDTIMEKEY : '
PRINT @MONTHENDTIMEKEY

DROP TABLE IF EXISTS #UPLOADID
SELECT UniqueUploadID INTO #UPLOADID FROM EXCELUPLOADHISTORY 
	WHERE CAST(DATEOFUPLOAD AS DATE)>@MONTHENDDATE
		AND AuthorisationStatus='A'

PRINT 'UPLOADID WHICH WILL NOT BE EFFECTED ON MONTH END : '

SELECT * FROM #UPLOADID

DROP TABLE IF EXISTS #CUSTOMERACID
SELECT DISTINCT CUSTOMERACID INTO #CUSTOMERACID 
FROM NPA_INTEGRATIONDETAILS_MOD WHERE UPLOADID IN (SELECT UniqueUploadID FROM #UPLOADID)--------------IT SHOULD BE START FROM 694--12--2424
AND EFFECTIVEFROMTIMEKEY=@MONTHENDTIMEKEY AND AUTHORISATIONSTATUS='A'

 


BEGIN TRAN
UPDATE A SET 
A.PROVSECURED = B.PROVSECURED
,A.PROVUNSECURED = B.PROVUNSECURED
,A.ADDLPROVISION = B.ADDLPROVISION
,A.PROVISIONALT_KEY = B.PROVISIONALT_KEY
,A.TOTALPROVISION = B.TOTALPROVISION
,A.SECUREDAMT = B.SECUREDAMT
,A.UNSECUREDAMT = B.UNSECUREDAMT
,A.SEC_PROVPER_OLD = B.SEC_PROVPER_OLD
,A.UNSEC_PROVPER_OLD = B.UNSEC_PROVPER_OLD
FROM 
(SELECT 
CUSTOMERACID
,PROVSECURED
,PROVUNSECURED
,ADDLPROVISION
,PROVISIONALT_KEY
,TOTALPROVISION
,SECUREDAMT
,UNSECUREDAMT
,SEC_PROVPER_OLD
,UNSEC_PROVPER_OLD FROM NPA_INTEGRATIONDETAILS(NOLOCK) 
WHERE EFFECTIVEFROMTIMEKEY=@MONTHENDTIMEKEY  AND EFFECTIVETOTIMEKEY=@MONTHENDTIMEKEY
AND CUSTOMERACID NOT IN (SELECT * FROM #CUSTOMERACID)
)
A INNER JOIN
(SELECT 
CUSTOMERACID
,PROVSECURED
,PROVUNSECURED
,ADDLPROVISION
,PROVISIONALT_KEY
,TOTALPROVISION
,SECUREDAMT
,UNSECUREDAMT
,SEC_PROVPER_OLD
,UNSEC_PROVPER_OLD FROM NPA_INTEGRATIONDETAILS_MONTH_END_JFM_2025(NOLOCK) 
WHERE EFFECTIVEFROMTIMEKEY=@MONTHENDTIMEKEY  AND EFFECTIVETOTIMEKEY=@MONTHENDTIMEKEY
AND CUSTOMERACID NOT IN (SELECT * FROM #CUSTOMERACID)
) B
ON A.CUSTOMERACID=B.CUSTOMERACID
WHERE 
ISNULL(A.PROVSECURED,0)			<> ISNULL(B.PROVSECURED,0)		
OR ISNULL(A.PROVUNSECURED,0)		<> ISNULL(B.PROVUNSECURED,0)		
OR ISNULL(A.ADDLPROVISION,0)		<> ISNULL(B.ADDLPROVISION,0)		
OR ISNULL(A.PROVISIONALT_KEY,0)	<> ISNULL(B.PROVISIONALT_KEY,0)	
OR ISNULL(A.TOTALPROVISION,0)		<> ISNULL(B.TOTALPROVISION,0)	
OR ISNULL(A.SECUREDAMT,0)			<> ISNULL(B.SECUREDAMT,0)		
OR ISNULL(A.UNSECUREDAMT,0)		<> ISNULL(B.UNSECUREDAMT,0)		
OR ISNULL(A.SEC_PROVPER_OLD,0)		<> ISNULL(B.SEC_PROVPER_OLD,0)	
OR ISNULL(A.UNSEC_PROVPER_OLD ,0)	<> ISNULL(B.UNSEC_PROVPER_OLD ,0)


COMMIT TRAN 
--6461865
END
GO