SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE Proc [dbo].[ETL_Validation]
As

begin

INSERT INTO ETL_Validation_Details(SYSTEM
,ENTERPRISE_CIF,CLIENT_ID,CUSTOMER_NAME,ACCOUNT_NUMBER,LIMIT,TOTAL_OUTSTANDING,PRINCIPAL_OUTSTANDING
,DPD,CLASSIFICATION,NPA_DATE,SETTLEMENT_STATUS,WRITE_OFF_FLAG,GROUP_ID,GROUP_CODE,GROUP_DESC
,SEGMENT,SUB_SEGMENT,PAN,AADHAR_UID,SCHEME_TYPE,SCHEME_CODE,SCHEME_DESCRIPTION,DRAWING_POWER
,DPD_OVERDUE_LOANS,DPD_INTEREST_NOT_SERVICED,DPD_OVERDRAWN,DPD_RENEWALS,OVERDUE_AMOUNT)
SELECT SYSTEM,ENTERPRISE_CIF,CLIENT_ID,CUSTOMER_NAME,ACCOUNT_NUMBER,LIMIT,TOTAL_OUTSTANDING,PRINCIPAL_OUTSTANDING
,DPD,CLASSIFICATION,NPA_DATE,SETTLEMENT_STATUS,WRITE_OFF_FLAG,GROUP_ID,GROUP_CODE,GROUP_DESC,SEGMENT,SUB_SEGMENT
,PAN,AADHAR_UID,SCHEME_TYPE,SCHEME_CODE,SCHEME_DESCRIPTION,DRAWING_POWER,DPD_OVERDUE_LOANS,DPD_INTEREST_NOT_SERVICED
,DPD_OVERDRAWN,DPD_RENEWALS,OVERDUE_AMOUNT FROM Induslnd_Stg.dbo.Finacle_Stg   WHERE CLASSIFICATION=''


------Prolendz----------


INSERT INTO ETL_Validation_Details(SYSTEM
,ENTERPRISE_CIF,CLIENT_ID,CUSTOMER_NAME,ACCOUNT_NUMBER,LIMIT,TOTAL_OUTSTANDING,PRINCIPAL_OUTSTANDING
,DPD,CLASSIFICATION,NPA_DATE,SETTLEMENT_STATUS,WRITE_OFF_FLAG,GROUP_ID,GROUP_CODE,GROUP_DESC
,SEGMENT,SUB_SEGMENT,PAN,AADHAR_UID,SCHEME_TYPE,SCHEME_CODE,SCHEME_DESCRIPTION,DRAWING_POWER
,DPD_OVERDUE_LOANS,DPD_INTEREST_NOT_SERVICED,DPD_OVERDRAWN,DPD_RENEWALS,OVERDUE_AMOUNT)
SELECT System,Cross_Dedupe_Match_Id,Customer_Code,Customer_Name,Deal_No
,Sanc_Limit,Outstanding,Principle_Outstanding,DPD,NPA_Status,NPA_Date
,Settlement_Status,Write_Off_Flag,Group_Id,Group_Code,Group_Desc,Segment
,Sub_Segment,PAN,Aadhaar_UID,Scheme_Type,Scheme_Code,Scheme_Code_Desc
,Drawing_Power,DPD_Overdue_Loans,DPD_Interest_Not_Serviced,DPD_OverDrawn,DPD_Renewals
,Overdue_Amount FROM Induslnd_Stg.dbo.Prolendz_Stg   WHERE  NPA_Status is null


 -------Accountis_npa_npadate_isnull---


 ------------ finacle---------

INSERT INTO ETL_Validation_Details(SYSTEM
,ENTERPRISE_CIF,CLIENT_ID,CUSTOMER_NAME,ACCOUNT_NUMBER,LIMIT,TOTAL_OUTSTANDING,PRINCIPAL_OUTSTANDING
,DPD,CLASSIFICATION,NPA_DATE,SETTLEMENT_STATUS,WRITE_OFF_FLAG,GROUP_ID,GROUP_CODE,GROUP_DESC
,SEGMENT,SUB_SEGMENT,PAN,AADHAR_UID,SCHEME_TYPE,SCHEME_CODE,SCHEME_DESCRIPTION,DRAWING_POWER
,DPD_OVERDUE_LOANS,DPD_INTEREST_NOT_SERVICED,DPD_OVERDRAWN,DPD_RENEWALS,OVERDUE_AMOUNT)
SELECT SYSTEM,ENTERPRISE_CIF,CLIENT_ID,CUSTOMER_NAME,ACCOUNT_NUMBER,LIMIT,TOTAL_OUTSTANDING,PRINCIPAL_OUTSTANDING
,DPD,CLASSIFICATION,NPA_DATE,SETTLEMENT_STATUS,WRITE_OFF_FLAG,GROUP_ID,GROUP_CODE,GROUP_DESC,SEGMENT,SUB_SEGMENT
,PAN,AADHAR_UID,SCHEME_TYPE,SCHEME_CODE,SCHEME_DESCRIPTION,DRAWING_POWER,DPD_OVERDUE_LOANS,DPD_INTEREST_NOT_SERVICED
,DPD_OVERDRAWN,DPD_RENEWALS,OVERDUE_AMOUNT FROM Induslnd_Stg.dbo.Finacle_Stg  where CLASSIFICATION<>001 and NPA_DATE=''


-----------Prolendz---------------

INSERT INTO ETL_Validation_Details(SYSTEM
,ENTERPRISE_CIF,CLIENT_ID,CUSTOMER_NAME,ACCOUNT_NUMBER,LIMIT,TOTAL_OUTSTANDING,PRINCIPAL_OUTSTANDING
,DPD,CLASSIFICATION,NPA_DATE,SETTLEMENT_STATUS,WRITE_OFF_FLAG,GROUP_ID,GROUP_CODE,GROUP_DESC
,SEGMENT,SUB_SEGMENT,PAN,AADHAR_UID,SCHEME_TYPE,SCHEME_CODE,SCHEME_DESCRIPTION,DRAWING_POWER
,DPD_OVERDUE_LOANS,DPD_INTEREST_NOT_SERVICED,DPD_OVERDRAWN,DPD_RENEWALS,OVERDUE_AMOUNT)
SELECT System,Cross_Dedupe_Match_Id,Customer_Code,Customer_Name,Deal_No
,Sanc_Limit,Outstanding,Principle_Outstanding,DPD,NPA_Status,NPA_Date
,Settlement_Status,Write_Off_Flag,Group_Id,Group_Code,Group_Desc,Segment
,Sub_Segment,PAN,Aadhaar_UID,Scheme_Type,Scheme_Code,Scheme_Code_Desc
,Drawing_Power,DPD_Overdue_Loans,DPD_Interest_Not_Serviced,DPD_OverDrawn,DPD_Renewals
,Overdue_Amount FROM Induslnd_Stg.dbo.Prolendz_Stg  where NPA_Status<>'S' and NPA_DATE=''


-------Finacle_TDA_(-ve)---------

INSERT INTO ETL_Validation_Details(SYSTEM
,ENTERPRISE_CIF,CLIENT_ID,CUSTOMER_NAME,ACCOUNT_NUMBER,LIMIT,TOTAL_OUTSTANDING,PRINCIPAL_OUTSTANDING
,DPD,CLASSIFICATION,NPA_DATE,SETTLEMENT_STATUS,WRITE_OFF_FLAG,GROUP_ID,GROUP_CODE,GROUP_DESC
,SEGMENT,SUB_SEGMENT,PAN,AADHAR_UID,SCHEME_TYPE,SCHEME_CODE,SCHEME_DESCRIPTION,DRAWING_POWER
,DPD_OVERDUE_LOANS,DPD_INTEREST_NOT_SERVICED,DPD_OVERDRAWN,DPD_RENEWALS,OVERDUE_AMOUNT)
SELECT SYSTEM,ENTERPRISE_CIF,CLIENT_ID,CUSTOMER_NAME,ACCOUNT_NUMBER,LIMIT,TOTAL_OUTSTANDING,PRINCIPAL_OUTSTANDING
,DPD,CLASSIFICATION,NPA_DATE,SETTLEMENT_STATUS,WRITE_OFF_FLAG,GROUP_ID,GROUP_CODE,GROUP_DESC,SEGMENT,SUB_SEGMENT
,PAN,AADHAR_UID,SCHEME_TYPE,SCHEME_CODE,SCHEME_DESCRIPTION,DRAWING_POWER,DPD_OVERDUE_LOANS,DPD_INTEREST_NOT_SERVICED
,DPD_OVERDRAWN,DPD_RENEWALS,OVERDUE_AMOUNT FROM Induslnd_Stg.dbo.Finacle_Stg where SCHEME_TYPE='TDA' AND cast(TOTAL_OUTSTANDING as decimal(20,2))<0

END
GO