SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE proc [dbo].[DedupSysDataTemp]
as
begin

DECLARE @TimeKey int = (SELECT TimeKey FROM SysDatamatrix  WHERE CurrentStatus='C')
insert into DedupSysData_Temp
(
NCIF,
SrcAppAlt_Key,
SrcAppCustomerID,
PAN
)
select 
ENTERPRISE_CIF AS NCIF,
CASE WHEN 
Ixsight_Stg.APPLICATION_CODE='GANASEVA' THEN 70
WHEN  Ixsight_Stg.APPLICATION_CODE='FINACLE'THEN 10
WHEN Ixsight_Stg.APPLICATION_CODE='CFD' THEN 60
WHEN Ixsight_Stg.APPLICATION_CODE='CRCARD' THEN 20
WHEN Ixsight_Stg.APPLICATION_CODE='CTFS' THEN 30
WHEN Ixsight_Stg.APPLICATION_CODE='TradePro' THEN 30
WHEN Ixsight_Stg.APPLICATION_CODE='ECS' THEN 20
WHEN Ixsight_Stg.APPLICATION_CODE='OPICS' THEN 40
ELSE '' END AS SrcAppAlt_Key,
APPLICATION_CIF AS SrcAppCustomerID,
PAN AS PAN
from  Induslnd_stg.dbo.Ixsight_Stg
WHERE APPLICATION_CODE IN ('GANASEVA','FINACLE','CFD','CRCARD','CTFS','TradePro','ECS','OPICS')
end
GO