SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO

CREATE PROCEDURE [dbo].[Rpt-ETLReconciliationReport]
@Date AS DATE
AS

--DECLARE @Date AS DATE=

SELECT 
 [GENRN_TIME_STAMP]
,[BATCH_ID]
,[COUNT_REC]
,[D2K_EXTRCTN_STATUS]
,[D2K_EXTRCTN_START_TIME]
,[D2K_EXTRCTN_END_TIME]
FROM HeaderTable
WHERE AS_ON_DATE=@Date

OPTION(RECOMPILE)
GO