SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE Proc [dbo].[Finacle_SCHEME_CODE_NUll]
as
Begin

Truncate table ETL_Validation_Details

insert into ETL_Validation_Details(
SYSTEM,ENTERPRISE_CIF,CLIENT_ID,CUSTOMER_NAME,ACCOUNT_NUMBER,LIMIT,TOTAL_OUTSTANDING,PRINCIPAL_OUTSTANDING
,DPD,CLASSIFICATION,NPA_DATE,SETTLEMENT_STATUS,WRITE_OFF_FLAG,GROUP_ID,GROUP_CODE,GROUP_DESC,SEGMENT
,SUB_SEGMENT,PAN,AADHAR_UID,SCHEME_TYPE,SCHEME_CODE,SCHEME_DESCRIPTION,DRAWING_POWER,DPD_OVERDUE_LOANS
,DPD_INTEREST_NOT_SERVICED,DPD_OVERDRAWN,DPD_RENEWALS,OVERDUE_AMOUNT)
select SYSTEM,ENTERPRISE_CIF,CLIENT_ID,CUSTOMER_NAME,ACCOUNT_NUMBER,LIMIT,TOTAL_OUTSTANDING,PRINCIPAL_OUTSTANDING
,DPD,CLASSIFICATION,NPA_DATE,SETTLEMENT_STATUS,WRITE_OFF_FLAG,GROUP_ID,GROUP_CODE,GROUP_DESC,SEGMENT
,SUB_SEGMENT,PAN,AADHAR_UID,SCHEME_TYPE,SCHEME_CODE,SCHEME_DESCRIPTION,DRAWING_POWER,DPD_OVERDUE_LOANS
,DPD_INTEREST_NOT_SERVICED,DPD_OVERDRAWN,DPD_RENEWALS,OVERDUE_AMOUNT from Induslnd_Stg.dbo.Finacle_Stg where SCHEME_CODE=''
End

GO