SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
CREATE PROCEDURE [dbo].[ETL Reconciliation Report]
@AS_ON_DATE DATE
AS
SET NOCOUNT ON;
SELECT [AS_ON_DATE]
,[GENRN_TIME_STAMP]
,[BATCH_ID][varchar]
,[COUNT_REC]
,[D2K_EXTRCTN_STATUS]
,[D2K_EXTRCTN_START_TIME]
,[D2K_EXTRCTN_END_TIME]
FROM HeaderTable
WHERE AS_ON_DATE=@AS_ON_DATE
GO