SET QUOTED_IDENTIFIER, ANSI_NULLS ON
GO


												
CREATE PROCEDURE [dbo].[PROVISION_COMPUTATION_REDUCTION_LIVE_REPORT_04042024]												
	@TIMEKEY INT 											
AS												
BEGIN												
												
SELECT PR.*,SEC_PROVPER_OLD,UNSEC_PROVPER_OLD FROM CURDAT.PROVISION_REDUCTION PR												
INNER JOIN NPA_INTEGRATIONDETAILS NID ON PR.CUSTOMERACID=NID.CUSTOMERACID												
WHERE PR.CUSTOMERACID IN (												
SELECT CUSTOMERACID FROM CURDAT.PROVISION_REDUCTION WHERE EffectiveFromTimeKey<=@TIMEKEY AND 												
												EffectiveToTimeKey>=@TIMEKEY)
												
	AND  NID.EffectiveFromTimeKey<=@TIMEKEY AND 											
		NID.EffectiveToTimeKey>=@TIMEKEY										
END	
GO