CREATE TABLE [dbo].[D2K_AADHAR_VOTER_NEW] (
  [COREWMSMRG_MATCHID] [varchar](50) NULL,
  [AADHAR_NO] [varchar](100) NULL,
  [KYCID] [varchar](80) NULL,
  [FRAUD_FLAG] [varchar](50) NULL
)
ON [PRIMARY]
GO