CREATE TABLE [dbo].[COLLATERAL_DELINK_DATE_AdvSecurityDetailL] (
  [ENTITYKEY] [bigint] NULL,
  [AccountEntityId] [int] NULL,
  [CustomerEntityId] [int] NULL,
  [SecurityType] [varchar](50) NULL,
  [CollateralType] [varchar](50) NULL,
  [SecurityAlt_Key] [smallint] NULL,
  [SecurityEntityID] [int] NOT NULL,
  [Security_RefNo] [varchar](50) NULL,
  [SecurityNature] [varchar](50) NULL,
  [SecurityChargeTypeAlt_Key] [int] NULL,
  [CurrencyAlt_Key] [smallint] NULL,
  [EntryType] [varchar](50) NULL,
  [ScrCrError] [varchar](50) NULL,
  [InwardNo] [smallint] NULL,
  [Limitnode_Flag] [varchar](50) NULL,
  [SrcSystemAlt_Key] [smallint] NULL,
  [RefCustomerId] [varchar](50) NULL,
  [RefSystemAcId] [varchar](50) NULL,
  [AuthorisationStatus] [varchar](50) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](50) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](50) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](50) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [datetime2](3) NULL,
  [MocTypeAlt_Key] [int] NULL,
  [MocStatus] [varchar](50) NULL,
  [MocDate] [smalldatetime] NULL,
  [SecurityParticular] [varchar](50) NULL,
  [OwnerTypeAlt_Key] [varchar](50) NULL,
  [AssetOwnerName] [varchar](50) NULL,
  [ValueAtSanctionTime] [decimal](16, 2) NULL,
  [BranchLastInspecDate] [date] NULL,
  [SatisfactionNo] [varchar](50) NULL,
  [SatisfactionDate] [date] NULL,
  [BankShare] [decimal](5, 2) NULL,
  [ActionTakenRemark] [varchar](50) NULL,
  [SecCharge] [varchar](50) NULL,
  [CollateralID] [varchar](50) NULL,
  [UCICID] [varchar](50) NULL,
  [CustomerName] [varchar](50) NULL,
  [TaggingAlt_Key] [int] NULL,
  [DistributionAlt_Key] [int] NULL,
  [CollateralCode] [varchar](50) NULL,
  [CollateralSubTypeAlt_Key] [int] NULL,
  [CollateralOwnerShipTypeAlt_Key] [int] NULL,
  [ChargeNatureAlt_Key] [int] NULL,
  [ShareAvailabletoBankAlt_Key] [int] NULL,
  [CollateralShareamount] [decimal](18, 2) NULL,
  [IfPercentagevalue_or_Absolutevalue] [decimal](16, 2) NULL,
  [CollateralValueatSanctioninRs] [decimal](18, 2) NULL,
  [CollateralValueasonNPAdateinRs] [decimal](18, 2) NULL,
  [ApprovedByFirstLevel] [varchar](50) NULL,
  [DateApprovedFirstLevel] [smalldatetime] NULL,
  [ChangeField] [varchar](50) NULL,
  [RefCustomer_CIF] [varchar](50) NULL,
  [COLL_DELINK_DATE] [date] NULL
)
ON [PRIMARY]
GO