CREATE TABLE [dbo].[AArtiDElink] (
  [date] [varchar](10) NOT NULL,
  [CustomerName] [varchar](500) NULL,
  [NCIF_Id] [varchar](100) NULL,
  [CustomerId] [varchar](20) NULL,
  [CustomerACID] [varchar](20) NULL,
  [MaxDPD] [int] NULL,
  [sourcename] [varchar](8) NOT NULL,
  [ProductCode] [varchar](50) NULL,
  [DPD_PrincOverdue] [int] NULL,
  [DPD_OtherOverdueSince] [int] NULL,
  [DPD_StockStmt] [int] NULL,
  [DPD_IntService] [int] NULL,
  [DPD_Renewals] [smallint] NULL,
  [DPD_Overdrawn] [smallint] NULL,
  [DPD_Interest_Not_Serviced] [smallint] NULL,
  [DPD_Overdue_Loans] [int] NULL,
  [OPEN_DATE] [date] NULL,
  [PrincOverdueSinceDt] [date] NULL,
  [IntNotServicedDt] [date] NULL,
  [ContiExcessDt] [date] NULL,
  [ReviewDueDt] [date] NULL,
  [OtherOverdueSinceDt] [date] NULL,
  [IntOverdueSinceDt] [date] NULL,
  [StkStmtDate] [date] NULL,
  [NCIF_AssetClassAlt_Key] [smallint] NULL,
  [balance] [decimal](16, 2) NULL,
  [PrincipleOutstanding] [decimal](16, 2) NULL,
  [Segment] [varchar](100) NULL,
  [DCCO_Date] [date] NULL,
  [PROJ_COMPLETION_DATE] [date] NULL,
  [COLL_DELINK_DATE] [date] NULL
)
ON [PRIMARY]
GO