CREATE TABLE [dbo].[HistoryDownGradeData_daily] (
  [AsonDate] [date] NULL,
  [SourceName] [varchar](50) NULL,
  [Account] [varchar](20) NULL,
  [Funded Non Funded Flag] [char](1) NULL,
  [CIF] [varchar](20) NULL,
  [NCIF] [varchar](100) NULL,
  [PAN No] [varchar](10) NULL,
  [Name] [varchar](500) NULL,
  [DPD_Overdue_Loans] [int] NULL,
  [DPD_Interest_Not_Serviced] [smallint] NULL,
  [DPD_Overdue Interest] [int] NULL,
  [DPD_Overdrawn] [smallint] NULL,
  [DPD_Principal Overdue] [int] NULL,
  [DPD_Other Overdue] [int] NULL,
  [DPD_Renewals] [smallint] NULL,
  [DPD_Stock Statement] [int] NULL,
  [Max DPD on date of downgrade] [int] NULL,
  [Date of downgrade] [date] NULL,
  [Date of NPA of source system] [date] NULL,
  [Homogenized_Date of NPA] [date] NULL,
  [Classification of source system] [varchar](20) NULL,
  [Homogenized_Classification] [varchar](20) NULL,
  [Principal OS] [decimal](16, 2) NULL,
  [Interest OS] [decimal](16, 2) NULL,
  [Yesterday Principal OS] [decimal](18, 2) NULL,
  [Yesterday Interest OS] [decimal](18, 2) NULL,
  [Scheme Type] [varchar](5) NULL,
  [Scheme_Code] [varchar](50) NULL,
  [Scheme Description] [varchar](100) NULL,
  [Segment] [varchar](100) NULL,
  [IS_MOC] [char](1) NULL,
  [Renewal Date] [date] NULL,
  [Stock statement date] [int] NULL,
  [DCCO date] [date] NULL,
  [Restructuring date] [date] NULL,
  [Restructuring Flag] [varchar](1) NULL,
  [Restructuring Type] [varchar](5000) NULL,
  [Fraud flag] [varchar](1) NULL,
  [Culprit System] [varchar](max) NULL,
  [Culprit System Account No] [varchar](max) NULL,
  [Stock statement date1] [date] NULL,
  [flgdeg] [char](1) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO