CREATE TABLE [dbo].[DIMPROVISIONPOLICY] (
  [Source_System] [nvarchar](50) NULL,
  [Source_Alt_Key] [int] NULL,
  [Scheme_Code] [nvarchar](50) NULL,
  [upto_3_months] [decimal](18, 6) NULL,
  [From_4_months_upto_6_months] [decimal](18, 6) NULL,
  [From_7_months_upto_9_months] [decimal](18, 6) NULL,
  [From_10_months_upto_12_months] [decimal](18, 6) NULL,
  [Doubtful_1] [decimal](18, 6) NULL,
  [Doubtful_2] [decimal](18, 6) NULL,
  [Doubtful_3] [decimal](18, 6) NULL,
  [Loss] [decimal](18, 6) NULL,
  [Effective_date] [nvarchar](50) NULL,
  [AuthorisationStatus] [nvarchar](50) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [nvarchar](50) NULL,
  [DateCreated] [datetime] NULL,
  [ModifiedBy] [nvarchar](50) NULL,
  [DateModified] [datetime] NULL,
  [ApprovedBy] [nvarchar](50) NULL,
  [DateApproved] [datetime] NULL,
  [D2Ktimestamp] [nvarchar](50) NULL,
  [ApprovedByFirstLevel] [nvarchar](50) NULL,
  [DateApprovedFirstLevel] [datetime] NULL,
  [ProvisionAlt_key] [int] NULL,
  [ProvisionUnSecured] [decimal](18, 6) NULL,
  [UploadID] [int] NULL,
  [Segment] [varchar](20) NULL
)
ON [PRIMARY]
GO