CREATE TABLE [dbo].[AdvAcRestructureDetail_Mod] (
  [EntityKey] [int] IDENTITY,
  [AccountEntityId] [int] NULL,
  [RestructureTypeAlt_Key] [smallint] NULL,
  [RestructureCatgAlt_Key] [smallint] NULL,
  [RestructureProposalDt] [date] NULL,
  [RestructureDt] [date] NULL,
  [RestructureAmt] [decimal] NULL,
  [ApprovingAuthAlt_Key] [varchar](10) NULL,
  [RestructureApprovalDt] [date] NULL,
  [RestructureSequenceRefNo] [int] NULL,
  [DiminutionAmount] [decimal] NULL,
  [RestructureByAlt_Key] [int] NULL,
  [RefCustomerId] [varchar](20) NULL,
  [RefSystemAcId] [varchar](30) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [OverDueSinceDt] [date] NULL,
  [BankApprovalDt] [date] NULL,
  [ForwardDt] [date] NULL,
  [Remark] [varchar](250) NULL,
  [ChangeFields] [varchar](100) NULL,
  [PreRestrucDefaultDate] [datetime] NULL,
  [PreRestrucAssetClass] [int] NULL,
  [PreRestrucNPA_Date] [datetime] NULL,
  [PostRestrucAssetClass] [int] NULL,
  [IntRepayStartDate] [datetime] NULL,
  [RefDate] [datetime] NULL,
  [InvocationDate] [datetime] NULL,
  [IsEquityCoversion] [char](1) NULL,
  [ConversionDate] [datetime] NULL,
  [Is_COVID_Morat] [varchar](5) NULL,
  [COVID_OTR_Catg] [varchar](10) NULL,
  [CRILIC_Fst_DefaultDate] [datetime] NULL,
  [FstDefaultReportingBank] [varchar](50) NULL,
  [ICA_SignDate] [datetime] NULL,
  [Is_InvestmentGrade] [varchar](20) NULL,
  [CreditProvision] [decimal](16, 2) NULL,
  [DFVProvision] [decimal](16, 2) NULL,
  [MTMProvision] [decimal](16, 2) NULL,
  [RevisedBusinessSegment] [varchar](30) NULL,
  [BankingType] [int] NULL,
  [RepaymentStartDate] [date] NULL,
  [DisbursementDate] [date] NULL,
  [RestructureAssetClassAlt_key] [int] NULL,
  [RestructureDate] [date] NULL,
  [Npa_Qtr] [varchar](20) NULL,
  [RestructurePOS] [decimal](16, 2) NULL,
  [RevisedBusSegAlt_Key] [int] NULL,
  [Restructure_NPA_Dt] [date] NULL,
  CONSTRAINT [PK_AdvAcRestructureDetail] PRIMARY KEY NONCLUSTERED ([EntityKey]) WITH (FILLFACTOR = 90)
)
ON [PRIMARY]
GO