CREATE TABLE [dbo].[temp1] (
  [NCIF_Id] [varchar](100) NULL,
  [SourceName] [varchar](50) NULL,
  [CustomerId] [varchar](20) NULL,
  [CustomerACID] [varchar](20) NULL,
  [PrincipleOutstanding] [decimal](16, 2) NULL,
  [Balance] [decimal](16, 2) NULL,
  [Segment] [varchar](100) NULL,
  [SubSegment] [varchar](100) NULL,
  [ProductCode] [varchar](50) NULL,
  [FacilityType] [varchar](10) NULL,
  [ProductDesc] [varchar](100) NULL,
  [CustomerName] [varchar](500) NULL,
  [DPD_Interest_Not_Serviced] [smallint] NULL,
  [DPD_IntService] [int] NULL,
  [DPD_OtherOverdueSince] [int] NULL,
  [DPD_Overdrawn] [smallint] NULL,
  [DPD_Overdue_Loans] [int] NULL,
  [DPD_PrincOverdue] [int] NULL,
  [DPD_Renewals] [smallint] NULL,
  [DPD_StockStmt] [int] NULL,
  [AC_AssetClassAlt_Key] [smallint] NULL,
  [AC_NPA_Date] [date] NULL,
  [NCIF_AssetClassAlt_Key] [smallint] NULL,
  [NCIF_NPA_Date] [date] NULL,
  [FlgDeg] [char](1) NOT NULL,
  [FlgUpg] [char](1) NOT NULL,
  [ARCFLAG] [varchar](1) NOT NULL,
  [IsRestructured] [varchar](1) NOT NULL,
  [OTS] [varchar](1) NOT NULL,
  [fraud] [varchar](1) NOT NULL,
  [FlgErosion] [varchar](1) NOT NULL,
  [StkStmtDate] [date] NULL,
  [Writeoffdate] [date] NULL,
  [WriteOffFlag] [char](1) NULL,
  [RestructureDt] [date] NULL,
  [Status] [varchar](9) NOT NULL,
  [Degradation] [varchar](1) NOT NULL,
  [Upgradation] [varchar](1) NOT NULL
)
ON [PRIMARY]
GO