CREATE TABLE [dbo].[BuyoutDetails_Mod] (
  [Entity_Key] [int] IDENTITY,
  [AsOnDate] [varchar](10) NULL,
  [PAN] [varchar](10) MASKED WITH (FUNCTION = 'default()') NULL,
  [NCIF_Id] [varchar](20) NULL,
  [CustomerName] [varchar](100) NULL,
  [CustomerACID] [varchar](30) MASKED WITH (FUNCTION = 'default()') NULL,
  [LoanAgreementNo] [varchar](100) NULL,
  [BuyoutPartyLoanNo] [varchar](40) NULL,
  [TotalOutstanding] [decimal](18, 2) NULL,
  [InterestReceivable] [decimal](18, 2) NULL,
  [PrincipalOutstanding] [decimal](18, 2) NULL,
  [FinalAssetClassAlt_Key] [smallint] NULL,
  [FinalNpaDt] [varchar](10) NULL,
  [DPD] [int] NULL,
  [SecurityValue] [decimal](18, 2) NULL,
  [Action] [varchar](5) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](100) NULL,
  [DateCreated] [datetime] NULL,
  [ModifyBy] [varchar](100) NULL,
  [DateModified] [date] NULL,
  [ApprovedBy] [varchar](100) NULL,
  [DateApproved] [date] NULL,
  [SummaryID] [int] NULL,
  [SrNo] [int] NULL,
  [UploadID] [int] NULL,
  [D2KTimeStamp] [timestamp],
  [AdditionalProvisionAmount] [decimal](16, 2) NULL,
  [AcceleratedProvisionPercentage] [decimal](16, 2) NULL,
  [SecuredStatus] [char](1) NULL,
  [ApprovedByFirstLevel] [varchar](100) NULL,
  [DateApprovedFirstLevel] [date] NULL
)
ON [PRIMARY]
GO