CREATE TABLE [dbo].[NPA_IntegrationDetails_MONTH_END_JFM_2024] (
  [EntityKey] [bigint] IDENTITY,
  [NCIF_Id] [varchar](100) NULL,
  [NCIF_Changed] [char](1) NULL,
  [SrcSysAlt_Key] [smallint] NULL,
  [NCIF_EntityID] [int] NOT NULL,
  [CustomerId] [varchar](20) NULL,
  [CustomerName] [varchar](500) NULL,
  [PAN] [varchar](10) NULL,
  [NCIF_AssetClassAlt_Key] [smallint] NULL,
  [NCIF_NPA_Date] [date] NULL,
  [AccountEntityID] [int] NOT NULL,
  [CustomerACID] [varchar](20) NULL,
  [SanctionedLimit] [decimal](18, 2) NULL,
  [DrawingPower] [decimal](16, 2) NULL,
  [PrincipleOutstanding] [decimal](16, 2) NULL,
  [Balance] [decimal](16, 2) NULL,
  [Overdue] [decimal](16, 2) NULL,
  [DPD_Overdue_Loans] [int] NULL,
  [DPD_Interest_Not_Serviced] [smallint] NULL,
  [DPD_Overdrawn] [smallint] NULL,
  [DPD_Renewals] [smallint] NULL,
  [MaxDPD] [int] NULL,
  [WriteOffFlag] [char](1) NULL,
  [Segment] [varchar](100) NULL,
  [SubSegment] [varchar](100) NULL,
  [ProductCode] [varchar](50) NULL,
  [ProductDesc] [varchar](100) NULL,
  [Settlement_Status] [varchar](20) NULL,
  [AC_AssetClassAlt_Key] [smallint] NULL,
  [AC_NPA_Date] [date] NULL,
  [AstClsChngByUser] [char](1) NULL,
  [AstClsChngDate] [datetime] NULL,
  [AstClsChngRemark] [varchar](100) NULL,
  [MOC_Status] [char](1) NULL,
  [MOC_Date] [smalldatetime] NULL,
  [MOC_ReasonAlt_Key] [varchar](100) NULL,
  [MOC_AssetClassAlt_Key] [smallint] NULL,
  [MOC_NPA_Date] [date] NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [MOC_Remark] [varchar](100) NULL,
  [D2Ktimestamp] [timestamp],
  [ProductType] [varchar](5) NULL,
  [ActualOutStanding] [decimal](16, 2) NULL,
  [MaxDPD_Type] [smallint] NULL,
  [ProductAlt_Key] [int] NULL,
  [AstClsAppRemark] [varchar](100) NULL,
  [MocAppRemark] [varchar](150) NULL,
  [PNPA_Status] [char](1) NULL,
  [PNPA_ReasonAlt_Key] [varchar](20) NULL,
  [PNPA_Date] [date] NULL,
  [ActualPrincipleOutstanding] [decimal](18, 2) NULL,
  [UNSERVED_INTEREST] [decimal](16, 2) NULL,
  [CUSTOMER_IDENTIFIER] [char](1) NULL,
  [ACCOUNT_LEVEL_CODE] [varchar](10) NULL,
  [NF_PNPA_Date] [date] NULL,
  [Remark] [varchar](500) NULL,
  [WriteOffDate] [date] NULL,
  [DbtDT] [date] NULL,
  [ErosionDT] [date] NULL,
  [FlgErosion] [varchar](1) NULL,
  [IntOverdue] [decimal](16, 2) NULL,
  [IntAccrued] [decimal](16, 2) NULL,
  [OtherOverdue] [decimal](16, 2) NULL,
  [PrincOverdue] [decimal](16, 2) NULL,
  [IsRestructured] [varchar](1) NULL,
  [IsOTS] [varchar](1) NULL,
  [IsTWO] [varchar](1) NULL,
  [IsARC_Sale] [varchar](1) NULL,
  [IsFraud] [varchar](1) NULL,
  [IsWiful] [varchar](1) NULL,
  [IsNonCooperative] [varchar](1) NULL,
  [IsSuitFiled] [varchar](1) NULL,
  [IsRFA] [varchar](1) NULL,
  [IsFITL] [varchar](1) NULL,
  [IsCentral_GovGty] [varchar](1) NULL,
  [Is_Oth_GovGty] [varchar](1) NULL,
  [BranchCode] [varchar](20) NULL,
  [FacilityType] [varchar](10) NULL,
  [SancDate] [date] NULL,
  [Region] [varchar](50) NULL,
  [State] [varchar](50) NULL,
  [Zone] [varchar](50) NULL,
  [NPA_TagDate] [date] NULL,
  [PS_NPS] [varchar](50) NULL,
  [Retail_Corpo] [varchar](10) NULL,
  [Area] [varchar](10) NULL,
  [FraudAmt] [numeric] NULL,
  [FraudDate] [date] NULL,
  [GovtGtyAmt] [decimal](16, 2) NULL,
  [GtyRepudiated] [varchar](1) NULL,
  [RepudiationDate] [date] NULL,
  [OTS_Amt] [decimal](16) NULL,
  [WriteOffAmount] [decimal](16, 2) NULL,
  [ARC_SaleDate] [date] NULL,
  [ARC_SaleAmt] [decimal](16, 2) NULL,
  [PrincOverdueSinceDt] [date] NULL,
  [IntNotServicedDt] [date] NULL,
  [ContiExcessDt] [date] NULL,
  [ReviewDueDt] [date] NULL,
  [OtherOverdueSinceDt] [date] NULL,
  [IntOverdueSinceDt] [date] NULL,
  [SecuredFlag] [varchar](1) NULL,
  [StkStmtDate] [date] NULL,
  [SecurityValue] [decimal](24) NULL,
  [DFVAmt] [decimal](16, 2) NULL,
  [CoverGovGur] [decimal](16, 2) NULL,
  [CreditsinceDt] [date] NULL,
  [DegReason] [varchar](max) NULL,
  [NetBalance] [decimal](16, 2) NULL,
  [ApprRV] [decimal](22, 2) NULL,
  [SecuredAmt] [decimal](16, 2) NULL,
  [UnSecuredAmt] [decimal](16, 2) NULL,
  [ProvDFV] [decimal](16, 2) NULL,
  [Provsecured] [decimal](16, 2) NULL,
  [ProvUnsecured] [decimal](16, 2) NULL,
  [ProvCoverGovGur] [decimal](16, 2) NULL,
  [AddlProvision] [decimal](16, 2) NULL,
  [TotalProvision] [decimal](16, 2) NULL,
  [BankProvsecured] [decimal](16, 2) NULL,
  [BankProvUnsecured] [decimal](16, 2) NULL,
  [BankTotalProvision] [decimal](16, 2) NULL,
  [RBIProvsecured] [decimal](18, 2) NULL,
  [RBIProvUnsecured] [decimal](18, 2) NULL,
  [RBITotalProvision] [decimal](18, 2) NULL,
  [SMA_Dt] [date] NULL,
  [UpgDate] [date] NULL,
  [ProvisionAlt_Key] [int] NULL,
  [PNPA_Reason] [varchar](max) NULL,
  [SMA_Class] [varchar](5) NULL,
  [SMA_Reason] [varchar](max) NULL,
  [CommonMocTypeAlt_Key] [smallint] NULL,
  [FlgDeg] [char](1) NULL,
  [FlgSMA] [char](1) NULL,
  [FlgPNPA] [char](1) NULL,
  [FlgUpg] [char](1) NULL,
  [FlgFITL] [char](1) NULL,
  [FlgAbinitio] [char](1) NULL,
  [NPA_Days] [int] NULL,
  [AppGovGur] [decimal](18, 2) NULL,
  [UsedRV] [decimal](18, 2) NULL,
  [ComputedClaim] [decimal](22, 2) NULL,
  [NPA_Reason] [varchar](max) NULL,
  [PnpaAssetClassAlt_key] [int] NULL,
  [SecApp] [char](1) NULL,
  [ProvPerSecured] [decimal](10, 4) NULL,
  [ProvPerUnSecured] [decimal](10, 4) NULL,
  [AddlProvisionPer] [decimal](6, 2) NULL,
  [FlgINFRA] [char](1) NULL,
  [MOCTYPE] [varchar](15) NULL,
  [DPD_IntService] [int] NULL,
  [DPD_StockStmt] [int] NULL,
  [DPD_FinMaxType] [varchar](50) NULL,
  [DPD_PrincOverdue] [int] NULL,
  [DPD_OtherOverdueSince] [int] NULL,
  [IsPUI] [char](1) NULL,
  [AC_Closed_Date] [date] NULL,
  [SECTOR] [varchar](50) NULL,
  [LossDT] [date] NULL,
  [IsFunded] [char](1) NULL,
  [UploadFlag] [char](1) NULL,
  [FlgProcessing] [char](1) NULL,
  [DCCO_Date] [date] NULL,
  [ACMOC_ReasonAlt_Key] [int] NULL,
  [FlgMOC] [char](1) NULL,
  [PROJ_COMPLETION_DATE] [date] NULL,
  [OPEN_DATE] [date] NULL,
  [UploadID] [int] NULL,
  [STD_ASSET_CAT_Alt_key] [smallint] NULL,
  [NatureofClassification] [char](1) NULL,
  [DateofImpacting] [date] NULL,
  [ImpactingAccountNo] [varchar](5000) NULL,
  [ImpactingSourceSystemName] [varchar](500) NULL,
  [Co_borrower_impacted] [varchar](1) NULL,
  [PBos_Culprit_Impact] [varchar](1) NULL
)
ON [PRIMARY]
TEXTIMAGE_ON [PRIMARY]
GO