CREATE TABLE [dbo].[D2K_AADHAR_VOTER_ALL_NEW_23012023_BKP] (
  [COREWMSMRG_MATCHID] [varchar](120) NULL,
  [AADHAR_NO] [varchar](120) NULL,
  [KYCTYPE] [varchar](120) NULL,
  [KYCID] [varchar](120) NULL,
  [VOTER_ID] [varchar](120) NULL,
  [PAN] [varchar](120) NULL
)
ON [PRIMARY]
GO