CREATE TABLE [dbo].[BuyoutFinalDetails_Mod] (
  [Entity_Key] [int] IDENTITY,
  [SummaryID] [int] NULL,
  [SlNo] [int] NULL,
  [AUNo] [varchar](30) NULL,
  [PoolName] [varchar](50) NULL,
  [Category] [varchar](50) NULL,
  [BuyoutPartyLoanNo] [varchar](40) NULL,
  [CustomerName] [varchar](100) NULL,
  [PAN] [varchar](10) MASKED WITH (FUNCTION = 'default()') NULL,
  [AadharNo] [varchar](12) NULL,
  [PrincipalOutstanding] [decimal](18, 2) NULL,
  [InterestReceivable] [decimal](18, 2) NULL,
  [Charges] [decimal](18, 2) NULL,
  [AccuredInterest] [decimal](18, 2) NULL,
  [DPD] [int] NULL,
  [AssetClass] [varchar](50) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [Changes] [varchar](200) NULL,
  [Remark] [varchar](200) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](100) NULL,
  [DateCreated] [date] NULL,
  [ModifyBy] [varchar](100) NULL,
  [DateModified] [date] NULL,
  [ApprovedBy] [varchar](100) NULL,
  [DateApproved] [date] NULL,
  [SecurityValue] [decimal](18, 2) NULL,
  [FinalNpaDt] [date] NULL,
  [FinalAssetClassAlt_Key] [smallint] NULL,
  [ProvisionAlt_Key] [smallint] NULL,
  [NetBalance] [decimal](18, 2) NULL,
  [ApprRV] [decimal](18, 2) NULL,
  [SecuredAmt] [decimal](18, 2) NULL,
  [UnSecuredAmt] [decimal](18, 2) NULL,
  [UsedRV] [decimal](18, 2) NULL,
  [Provsecured] [decimal](18, 2) NULL,
  [ProvUnsecured] [decimal](18, 2) NULL,
  [TotalProvision] [decimal](18, 2) NULL,
  [FLGDEG] [char](1) NULL,
  [FLGUPG] [char](1) NULL,
  [DegReason] [varchar](500) NULL,
  [UpgDate] [date] NULL,
  [NCIF_Id] [varchar](20) NULL,
  [CustomerACID] [varchar](30) MASKED WITH (FUNCTION = 'default()') NULL,
  [LoanAgreementNo] [varchar](100) NULL,
  [Action] [varchar](5) NULL,
  [D2KTimeStamp] [timestamp],
  [TotalOutstanding] [decimal](18, 2) NULL
)
ON [PRIMARY]
GO