CREATE TABLE [dbo].[NPA_IntegrationBillDetails_Temp] (
  [EntityKey] [int] IDENTITY,
  [NCIF_Id] [varchar](20) NULL,
  [NCIF_Changed] [char](1) NULL,
  [SrcSysAlt_Key] [smallint] NULL,
  [NCIF_EntityID] [int] NOT NULL,
  [CustomerId] [varchar](20) NULL,
  [CustomerName] [varchar](80) NULL,
  [PAN] [varchar](10) MASKED WITH (FUNCTION = 'default()') NULL,
  [AddharNo] [varchar](12) NULL,
  [BillNo] [varchar](20) NULL,
  [GroupId] [varchar](10) NULL,
  [GroupCode] [varchar](10) NULL,
  [GroupDesc] [varchar](100) NULL,
  [AccountEntityID] [int] NOT NULL,
  [CustomerACID] [varchar](20) MASKED WITH (FUNCTION = 'default()') NULL,
  [SanctionedLimit] [decimal](18, 2) NULL,
  [DrawingPower] [decimal](16, 2) NULL,
  [PrincipleOutstanding] [decimal](16, 2) NULL,
  [Balance] [decimal](16, 2) NULL,
  [Overdue] [decimal](16, 2) NULL,
  [DPD_Overdue_Loans] [smallint] NULL,
  [DPD_Interest_Not_Serviced] [smallint] NULL,
  [DPD_Overdrawn] [smallint] NULL,
  [DPD_Renewals] [smallint] NULL,
  [DPD] [smallint] NULL,
  [MaxDPD] [smallint] NULL,
  [WriteOffFlag] [char](1) NULL,
  [Segment] [varchar](100) NULL,
  [SubSegment] [varchar](100) NULL,
  [ProductCode] [varchar](50) NULL,
  [ProductDesc] [varchar](100) NULL,
  [ProductType] [varchar](5) NULL,
  [Settlement_Status] [varchar](20) NULL,
  [AuthorisationStatus] [varchar](2) NULL,
  [EffectiveFromTimeKey] [int] NOT NULL,
  [EffectiveToTimeKey] [int] NOT NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [RejectRemark] [varchar](100) NULL,
  [D2Ktimestamp] [timestamp]
)
ON [PRIMARY]
GO