CREATE TABLE [dbo].[ExtDataMatrix_MOD] (
  [Entity_Key] [int] IDENTITY,
  [TimeKey] [int] NULL,
  [CurrentStatus] [char](1) NULL DEFAULT ('N'),
  [MOC_Initialised] [char](1) NULL,
  [MOC_Frozen] [char](1) NULL,
  [QTR_Initialised] [char](1) NULL,
  [QTR_Frozen] [char](1) NULL,
  [MOC_Freeze] [char](1) NULL,
  [MOC_FreezeDate] [date] NULL,
  [ETL_Completed] [varchar](20) NULL,
  [ETL_CompletedDate] [date] NULL,
  [PreProcessingFreeze] [char](1) NULL,
  [PreProcessingFreezeDate] [date] NULL,
  [ProcessingStatus] [char](1) NULL,
  [ProcessingDate] [date] NULL,
  [PreProcessingFreezeBy] [varchar](20) NULL,
  [MOC_FreezeBy] [varchar](20) NULL,
  [Finacle_Reverse] [char](1) NULL,
  [ECS_Reverse] [char](1) NULL,
  [Prolendz_Reverse] [char](1) NULL,
  [Ganseca_Reverse] [char](1) NULL,
  [Calypso_Reverse] [char](1) NULL,
  [PNPA_Status] [char](1) NULL,
  [AuthorisationStatus] [char](2) NULL,
  [EffectiveFromTimeKey] [int] NULL,
  [EffectiveToTimeKey] [int] NULL,
  [CreatedBy] [varchar](20) NULL,
  [DateCreated] [smalldatetime] NULL,
  [ModifiedBy] [varchar](20) NULL,
  [DateModified] [smalldatetime] NULL,
  [ApprovedBy] [varchar](20) NULL,
  [DateApproved] [smalldatetime] NULL,
  [D2Ktimestamp] [timestamp],
  [Remark] [varchar](500) NULL,
  [ExtDate] [date] NULL
)
ON [PRIMARY]
GO