CREATE TABLE [dbo].[WOFF_JANFEB_2024] (
  [RN] [bigint] NULL,
  [InsertDate] [datetime2](3) NOT NULL,
  [AsonDate] [date] NOT NULL,
  [SourceName] [varchar](150) NULL,
  [Account No] [varchar](20) NULL,
  [CIF] [varchar](20) NULL,
  [NCIF] [varchar](100) NULL,
  [Pan] [varchar](10) NULL,
  [CustomerName] [varchar](500) NULL,
  [DPD_Overdue_Loans] [int] NULL,
  [DPD_Interest_Not_Serviced] [smallint] NULL,
  [DPD_Overdue Interest] [smallint] NULL,
  [DPD_Overdrawn] [smallint] NULL,
  [DPD_Principal Overdue] [int] NULL,
  [DPD_Other Overdue] [int] NULL,
  [DPD_Renewals] [smallint] NULL,
  [DPD_Stock Statement] [int] NULL,
  [Max DPD on date of write off] [int] NULL,
  [Date of Write off by D2K] [date] NULL,
  [Principal OS] [decimal](16, 2) NULL,
  [Interest OS] [decimal](16, 2) NULL,
  [NCIF NPA date prior to write off] [date] NULL,
  [Asset class prior to write off] [smallint] NULL,
  [Scheme_Type] [varchar](5) NULL,
  [Scheme_Code] [varchar](50) NULL,
  [Scheme Description] [varchar](100) NULL,
  [Segment] [varchar](100) NULL,
  [IS_MOC] [char](1) NULL,
  [Renewal Date] [date] NULL,
  [Stock statement date] [date] NULL,
  [DCCO date] [date] NULL,
  [Restructuring date] [date] NULL,
  [NPA Date NCIF] [date] NULL,
  [Fraud Flag] [varchar](1) NULL,
  [Woff Flag] [varchar](1) NULL,
  [ARC Flag] [varchar](1) NULL,
  [OTS Flag] [varchar](1) NULL,
  [WriteOffAmount] [decimal](18, 2) NULL,
  [MocReasonName] [varchar](200) NULL
)
ON [PRIMARY]
GO